# Generated by Django 5.1.7 on 2025-05-16 05:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ClientPurchaseOrder', '0001_initial'),
        ('Create_New_Item', '0001_initial'),
        ('Pincode', '0001_initial'),
        ('Sales_Person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, choices=[('0', 'Due on Receipt'), ('15', 'Net 15'), ('30', 'Net 30'), ('45', 'Net 45'), ('60', 'Net 60')], default='30', help_text='Select payment term (e.g., Net 30)', max_length=5, null=True)),
                ('party_name', models.CharField(blank=True, max_length=255)),
                ('party_mobile_number', models.CharField(blank=True, max_length=15)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('partially paid', 'Partially Paid'), ('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=15)),
                ('total_paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', to='Pincode.addparty')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='ClientPurchaseOrder.clientpurchaseorder')),
                ('sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', to='Sales_Person.salesperson')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoiceEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='Sales_Invoice.salesinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('hsn_sac_code', models.CharField(blank=True, max_length=20, null=True)),
                ('measuring_unit', models.CharField(blank=True, max_length=10)),
                ('price_per_item', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoice_items', to='Create_New_Item.productitem')),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoice_items', to='Sales_Invoice.salesinvoice')),
                ('service_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoice_services', to='Create_New_Item.serviceitem')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Create_New_Item.gsttax')),
            ],
        ),
        migrations.CreateModel(
            name='TotalAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sales_invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='total_amount', to='Sales_Invoice.salesinvoice')),
            ],
        ),
    ]
