# Generated by Django 5.1.7 on 2025-06-12 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0003_employee_streams"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdministrativeTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_id", models.CharField(blank=True, max_length=50, unique=True)),
                ("subject", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("password_change", "Password Change"),
                            ("username_change", "Username Change"),
                            ("location_change", "Location Change"),
                            ("shift_change", "Shift Change"),
                            ("team_related", "Team Related"),
                            ("task_related", "Task Related"),
                            ("project_related", "Project Related"),
                            ("others", "Others"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="tickets/administrative/"
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Request", "Request"),
                            ("Review", "Review"),
                            ("Approved", "Approved"),
                        ],
                        default="Request",
                        max_length=20,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_administrative_tickets",
                        to="authentication.employee",
                    ),
                ),
                (
                    "hr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_administrative_tickets",
                        to="authentication.hr",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="administrative_tickets",
                        to="authentication.manager",
                    ),
                ),
                (
                    "raise_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admin_tickets",
                        to="authentication.admin",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_administrative_tickets",
                        to="authentication.supervisor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_id", models.CharField(blank=True, max_length=50, unique=True)),
                ("subject", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("task_late_submission", "Task Late Submission"),
                            ("project_materials", "Project Materials"),
                            ("team_conflicts", "Team Conflicts"),
                            ("risk_management", "Risk Management"),
                            ("project_deadline", "Project Deadline"),
                            ("project_plan", "Project Plan"),
                            ("resource_allocation", "Resource Allocation"),
                            ("others", "Others"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="tickets/employee/"
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Request", "Request"),
                            ("Review", "Review"),
                            ("Approved", "Approved"),
                        ],
                        default="Request",
                        max_length=20,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "raise_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_tickets",
                        to="authentication.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HRTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_id", models.CharField(blank=True, max_length=50, unique=True)),
                ("subject", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("leave_policy", "Leave Policy"),
                            ("leave_request_related", "Leave Request Related"),
                            ("login_issue", "Login Issue"),
                            ("salary_related", "Salary Related"),
                            ("attendance_related", "Attendance Related"),
                            ("training_conflicts", "Training Conflicts"),
                            ("others", "Others"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="tickets/hr/"),
                ),
                ("hr_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Request", "Request"),
                            ("Review", "Review"),
                            ("Approved", "Approved"),
                        ],
                        default="Request",
                        max_length=20,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_hr_tickets",
                        to="authentication.employee",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_related_tickets",
                        to="authentication.manager",
                    ),
                ),
                (
                    "raise_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hr_tickets",
                        to="authentication.hr",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_hr_tickets",
                        to="authentication.supervisor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManagerTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_id", models.CharField(blank=True, max_length=50, unique=True)),
                ("subject", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("task_late_submission", "Task Late Submission"),
                            ("project_materials", "Project Materials"),
                            ("team_conflicts", "Team Conflicts"),
                            ("risk_management", "Risk Management"),
                            ("project_deadline", "Project Deadline"),
                            ("project_plan", "Project Plan"),
                            ("resource_allocation", "Resource Allocation"),
                            ("others", "Others"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="tickets/manager/"
                    ),
                ),
                ("manager_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Request", "Request"),
                            ("Review", "Review"),
                            ("Approved", "Approved"),
                        ],
                        default="Request",
                        max_length=20,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_manager_tickets",
                        to="authentication.employee",
                    ),
                ),
                (
                    "raise_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manager_tickets",
                        to="authentication.manager",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OtherTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_id", models.CharField(blank=True, max_length=50, unique=True)),
                ("subject", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("service_type", models.CharField(blank=True, max_length=100)),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="tickets/other/"),
                ),
                ("user_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Request", "Request"),
                            ("Review", "Review"),
                            ("Approved", "Approved"),
                        ],
                        default="Request",
                        max_length=20,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_other_tickets",
                        to="authentication.employee",
                    ),
                ),
                (
                    "hr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_other_tickets",
                        to="authentication.hr",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_related_tickets",
                        to="authentication.manager",
                    ),
                ),
                (
                    "raise_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="other_tickets",
                        to="authentication.admin",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_other_tickets",
                        to="authentication.supervisor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupervisorTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_id", models.CharField(blank=True, max_length=50, unique=True)),
                ("subject", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("reports_of_project", "Reports of Project"),
                            ("reports_of_tasks", "Reports of Tasks"),
                            ("team_conflicts", "Team Conflicts"),
                            ("communication_issue", "Communication Issue"),
                            ("performance_related", "Performance Related"),
                            ("others", "Others"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="tickets/supervisor/"
                    ),
                ),
                (
                    "supervisor_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Request", "Request"),
                            ("Review", "Review"),
                            ("Approved", "Approved"),
                        ],
                        default="Request",
                        max_length=20,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_supervisor_tickets",
                        to="authentication.employee",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_related_tickets",
                        to="authentication.manager",
                    ),
                ),
                (
                    "raise_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supervisor_tickets",
                        to="authentication.supervisor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_id", models.CharField(blank=True, max_length=50, unique=True)),
                ("subject", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("slow_network", "Slow Network"),
                            ("system_performance", "System Performance"),
                            ("cyber_hacks", "Cyber Hacks"),
                            ("data_loss", "Data Loss"),
                            ("software_issue", "Software Compatibility Issues"),
                            ("trouble_shoot", "Trouble Shoot"),
                            ("hardware_issue", "Hardware Issue"),
                            ("others", "Others"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="tickets/system/"
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Request", "Request"),
                            ("Review", "Review"),
                            ("Approved", "Approved"),
                        ],
                        default="Request",
                        max_length=20,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_system_tickets",
                        to="authentication.employee",
                    ),
                ),
                (
                    "hr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_system_tickets",
                        to="authentication.hr",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_related_tickets",
                        to="authentication.manager",
                    ),
                ),
                (
                    "raise_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="system_tickets",
                        to="authentication.admin",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_system_tickets",
                        to="authentication.supervisor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("reply_text", models.TextField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
