# Generated by Django 5.1.7 on 2025-09-11 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_superadmin_features"),
        ("helpdesk", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_id", models.CharField(blank=True, max_length=50, unique=True)),
                ("subject", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("leave_policy", "Leave Policy"),
                            ("leave_request_related", "Leave Request Related"),
                            ("login_issue", "Login Issue"),
                            ("salary_related", "Salary Related"),
                            ("attendance_related", "Attendance Related"),
                            ("training_conflicts", "Training Conflicts"),
                            ("reports_of_project", "Reports of Project"),
                            ("reports_of_tasks", "Reports of Tasks"),
                            ("team_conflicts", "Team Conflicts"),
                            ("communication_issue", "Communication Issue"),
                            ("performance_related", "Performance Related"),
                            ("task_late_submission", "Task Late Submission"),
                            ("project_materials", "Project Materials"),
                            ("risk_management", "Risk Management"),
                            ("project_deadline", "Project Deadline"),
                            ("project_plan", "Project Plan"),
                            ("resource_allocation", "Resource Allocation"),
                            ("others", "Others"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="tickets/user/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Request", "Request"),
                            ("Review", "Review"),
                            ("Approved", "Approved"),
                        ],
                        default="Request",
                        max_length=20,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets_created",
                        to="authentication.user",
                    ),
                ),
                (
                    "raise_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets_received",
                        to="authentication.user",
                    ),
                ),
            ],
        ),
    ]
