# Generated by Django 5.1.7 on 2025-05-16 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sales_Person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('opening_balance_to_collect', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('opening_balance_to_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gstin', models.CharField(max_length=15, unique=True)),
                ('pan_number', models.CharField(max_length=10, unique=True)),
                ('party_type', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier')], max_length=50)),
                ('party_category', models.TextField()),
                ('credit_period_days', models.IntegerField(default=0)),
                ('credit_limit_rupees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties', to='Sales_Person.salesperson')),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='Pincode.addparty')),
            ],
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='Pincode.addparty')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('is_same_as_billing_address', models.BooleanField(default=False)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='Pincode.addparty')),
            ],
        ),
    ]
