# Generated by Django 5.1.7 on 2025-05-16 05:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Create_New_Item', '0001_initial'),
        ('Pincode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('order_date', models.DateField(default=django.utils.timezone.localdate)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('vendor_mobile_number', models.CharField(blank=True, max_length=15)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('vendor', models.ForeignKey(limit_choices_to={'party_type': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='Pincode.addparty')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='purchase_order.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_hsn', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_before_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_after_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Create_New_Item.gsttax')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Create_New_Item.productitem')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase_order.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderTotalAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_before_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='total_amount', to='purchase_order.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='VendorInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='vendor_invoices/')),
                ('total_before_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('supplier_to_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('purchase_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_invoices', to='purchase_order.purchaseorder')),
                ('vendor', models.ForeignKey(blank=True, limit_choices_to={'party_type': 'supplier'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_invoices', to='Pincode.addparty')),
            ],
        ),
        migrations.CreateModel(
            name='VendorInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_hsn', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_before_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_after_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Create_New_Item.gsttax')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Create_New_Item.productitem')),
                ('vendor_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase_order.vendorinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='VendorInvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI'), ('Cheque', 'Cheque'), ('Other', 'Other')], default='Cash', max_length=50)),
                ('payment_out_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='vendor_invoice_payments/')),
                ('vendor', models.ForeignKey(limit_choices_to={'party_type': 'supplier'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_invoice_payments', to='Pincode.addparty')),
                ('vendor_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='purchase_order.vendorinvoice')),
            ],
        ),
    ]
