# Generated by Django 5.1.7 on 2025-05-16 05:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Create_New_Item', '0001_initial'),
        ('Pincode', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('po_date', models.DateField(default=django.utils.timezone.localdate)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_mobile_number', models.CharField(blank=True, max_length=15)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('po_file_upload', models.FileField(blank=True, null=True, upload_to='client_purchase_orders/')),
                ('status', models.CharField(choices=[('received', 'Received'), ('converted', 'Converted into Sales Order')], default='received', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(limit_choices_to={'party_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_purchase_orders', to='Pincode.addparty')),
                ('sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientPurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_before_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_after_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Create_New_Item.gsttax')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Create_New_Item.productitem')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ClientPurchaseOrder.clientpurchaseorder')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Create_New_Item.serviceitem')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPurchaseOrderTotalAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_before_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='total_amount', to='ClientPurchaseOrder.clientpurchaseorder')),
            ],
        ),
    ]
