# Generated by Django 5.1.7 on 2025-05-16 05:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GSTTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('gst_rate', models.DecimalField(decimal_places=2, help_text='GST Rate (%)', max_digits=5)),
                ('cess_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Cess Rate (%)', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='HSNCode',
            fields=[
                ('hsn_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SACCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sac_code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('sales_price_without_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sales_price_with_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gst_tax_rate', models.CharField(choices=[('exempted', 'Exempted'), ('0', 'GST @ 0%'), ('0.1', 'GST @ 0.1%'), ('0.25', 'GST @ 0.25%'), ('1.5', 'GST @ 1.5%'), ('3', 'GST @ 3%'), ('5', 'GST @ 5%'), ('6', 'GST @ 6%'), ('12', 'GST @ 12%'), ('13.8', 'GST @ 13.8%'), ('18', 'GST @ 18%'), ('14_12', 'GST @ 14% + Cess @ 12%'), ('28', 'GST @ 28%'), ('28_12', 'GST @ 28% + Cess @ 12%'), ('28_60', 'GST @ 28% + Cess @ 60%')], max_length=10)),
                ('opening_stock', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('measuring_unit', models.CharField(choices=[('UNT', 'Units'), ('UGS', 'US Gallons'), ('KGS', 'Kilograms'), ('LTR', 'Liters'), ('AAN', 'Aanna'), ('ACS', 'Accessories'), ('AC', 'Acre'), ('AMP', 'Ampoule'), ('BAG', 'Bags'), ('BAL', 'Bale'), ('BALL', 'Balls'), ('BAR', 'Barni'), ('BOU', 'Billions Of Units'), ('BLISTER', 'Blister'), ('BOLUS', 'Bolus'), ('BK', 'Book'), ('BOR', 'Bora'), ('BTL', 'Bottles'), ('BOX', 'Box'), ('BRASS', 'Brass'), ('BRICK', 'Brick'), ('BCK', 'Buckets'), ('BKL', 'Buckles'), ('BUN', 'Bunches'), ('BDL', 'Bundles'), ('CAN', 'Cans'), ('CAP', 'Cap'), ('CPS', 'Capsules'), ('CT', 'Carat'), ('CTS', 'Carats'), ('CARD', 'Card'), ('CTN', 'Cartons'), ('CASE', 'Case'), ('CMS', 'Centimeter'), ('CNT', 'Cents'), ('CHAIN', 'Chain'), ('CHOKA', 'Choka'), ('CHUDI', 'Chudi'), ('CLT', 'Cloth'), ('COIL', 'Coil'), ('CONT', 'Container'), ('COPY', 'Copy'), ('COURSE', 'Course'), ('CRT', 'Crate'), ('CRM', 'Cream'), ('CCM', 'Cubic Centimeter'), ('CUFT', 'Cubic Feet'), ('CFM', 'Cubic Feet Per Minute'), ('CFT', 'Cubic Foot'), ('CBM', 'Cubic Meter'), ('CUP', 'Cup'), ('CV', 'Cv'), ('DAILY', 'Daily'), ('DANGLER', 'Dangler'), ('DAY', 'Day'), ('DEZ', 'Daze'), ('DOZ', 'Dozen'), ('DROP', 'Drop'), ('DRM', 'Drum'), ('EA', 'Each'), ('EACH', 'Each'), ('FT', 'Feet'), ('FT2', 'Feet Square'), ('FIT', 'Fit'), ('FLD', 'Fold'), ('FREE', 'Free'), ('FTS', 'Fts'), ('GEL', 'Gel'), ('GLS', 'Glasses'), ('GMS', 'Grams'), ('GGR', 'Great Gross'), ('GRS', 'Gross'), ('GYD', 'Gross Yards'), ('HF', 'Half'), ('HEGAR', 'Hanger'), ('HA', 'Hectare'), ('HMT', 'Helmet'), ('HRS', 'Hours'), ('INJECTION', 'Injection'), ('IN', 'Inches'), ('ITEM ID', 'Item Id'), ('JAR', 'Jars'), ('JL', 'Jhal'), ('JO', 'Jhola'), ('JHL', 'Jhola Jhal'), ('JOB', 'Job'), ('KT', 'Katta'), ('KGS', 'Kilograms'), ('KLR', 'Kiloliter'), ('KME', 'Kilometre'), ('KMS', 'Kilometres'), ('KVA', 'Kilovolt-amp'), ('KW', 'Kilowatt'), ('KIT', 'Kit'), ('LAD', 'Ladi'), ('LENG', 'Length'), ('LBS', 'Libra Pondo'), ('LTR', 'Litre'), ('LOT', 'Lot'), ('LS', 'Lump Sum'), ('MAN-DAY', 'Man-days'), ('MRK', 'Mark'), ('MBPS', 'Mbps'), ('MTR', 'Meters'), ('MMBTU', 'Metric Million British Thermal Unit'), ('MTON', 'Metric Ton'), ('MG', 'Microgram'), ('M/C', 'Millicoulomb'), ('MLG', 'Milligram'), ('MLT', 'Millilitre'), ('MM', 'Millimeter'), ('MINS', 'Minutes'), ('MONTH', 'Month'), ('MON', 'Months'), ('MORA', 'Mora'), ('NIGHT', 'Night'), ('NONE', 'None'), ('NOS', 'Numbers'), ('OINT', 'Ointment'), ('OTH', 'Others'), ('OR', 'Outer'), ('PKG', 'Package'), ('PKT', 'Packets'), ('PAC', 'Packs'), ('PAD', 'Pad'), ('PADS', 'Pads'), ('PAGE', 'Pages'), ('PAIR', 'Pair'), ('PRS', 'Pairs'), ('PATTA', 'Patta'), ('PAX', 'Pax'), ('PER', 'Per'), ('PWP', 'Per Watt Peak'), ('PERSON', 'Persons'), ('PET', 'Peti'), ('PHILE', 'Phile'), ('PCS', 'Pieces'), ('PLT', 'Plates'), ('PT', 'Point'), ('PRT', 'Portion'), ('POCH', 'Pouch'), ('QUAD', 'Quad'), ('QTY', 'Quantity'), ('QTL', 'Quintal'), ('RTI', 'Ratti'), ('REAM', 'Ream'), ('REEL', 'Reel'), ('RIM', 'Rim'), ('ROL', 'Rolls'), ('ROOM', 'Room'), ('RFT', 'Running Foot'), ('RMT', 'Running Meter'), ('RS', 'Rupees'), ('SAC', 'Sachet'), ('SEC', 'Seconds'), ('SEM', 'Semester'), ('SSN', 'Session'), ('SET', 'Sets'), ('SHEET', 'Sheet'), ('SKINS', 'Skins'), ('SLEVES', 'Sleeves'), ('SPRAY', 'Spray'), ('SQCM', 'Square Centimeters'), ('SQF', 'Square Feet'), ('SQY', 'Square Yards'), ('SARAM', 'Saram'), ('STICKER', 'Stickers'), ('STONE', 'Stone'), ('STRP', 'Strips'), ('SYRP', 'Syrup'), ('TBS', 'Tablets'), ('TGM', 'Ten Gross'), ('TKT', 'Ticket'), ('TIN', 'Tin'), ('TON', 'Tonnes'), ('TRY', 'Trays'), ('TRIP', 'Trp'), ('TRK', 'Truck'), ('TUB', 'Tubes'), ('UNT', 'Units'), ('UGS', 'US Gallons'), ('VIAL', 'Vials'), ('W', 'Watt'), ('WEEK', 'Week'), ('YDS', 'Yards'), ('YRS', 'Years')], max_length=10)),
                ('service_code', models.CharField(max_length=50, unique=True)),
                ('final_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_description', models.TextField(blank=True, null=True)),
                ('sac_code', models.CharField(default='default_sac_code', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('product_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('gst_tax_rate', models.CharField(blank=True, choices=[('exempted', 'Exempted'), ('0', 'GST @ 0%'), ('0.1', 'GST @ 0.1%'), ('0.25', 'GST @ 0.25%'), ('1.5', 'GST @ 1.5%'), ('3', 'GST @ 3%'), ('5', 'GST @ 5%'), ('6', 'GST @ 6%'), ('12', 'GST @ 12%'), ('13.8', 'GST @ 13.8%'), ('18', 'GST @ 18%'), ('14_12', 'GST @ 14% + Cess @ 12%'), ('28', 'GST @ 28%'), ('28_12', 'GST @ 28% + Cess @ 12%'), ('28_60', 'GST @ 28% + Cess @ 60%')], max_length=10, null=True)),
                ('measuring_unit', models.CharField(choices=[('UNT', 'Units'), ('UGS', 'US Gallons'), ('KGS', 'Kilograms'), ('LTR', 'Liters'), ('AAN', 'Aanna'), ('ACS', 'Accessories'), ('AC', 'Acre'), ('AMP', 'Ampoule'), ('BAG', 'Bags'), ('BAL', 'Bale'), ('BALL', 'Balls'), ('BAR', 'Barni'), ('BOU', 'Billions Of Units'), ('BLISTER', 'Blister'), ('BOLUS', 'Bolus'), ('BK', 'Book'), ('BOR', 'Bora'), ('BTL', 'Bottles'), ('BOX', 'Box'), ('BRASS', 'Brass'), ('BRICK', 'Brick'), ('BCK', 'Buckets'), ('BKL', 'Buckles'), ('BUN', 'Bunches'), ('BDL', 'Bundles'), ('CAN', 'Cans'), ('CAP', 'Cap'), ('CPS', 'Capsules'), ('CT', 'Carat'), ('CTS', 'Carats'), ('CARD', 'Card'), ('CTN', 'Cartons'), ('CASE', 'Case'), ('CMS', 'Centimeter'), ('CNT', 'Cents'), ('CHAIN', 'Chain'), ('CHOKA', 'Choka'), ('CHUDI', 'Chudi'), ('CLT', 'Cloth'), ('COIL', 'Coil'), ('CONT', 'Container'), ('COPY', 'Copy'), ('COURSE', 'Course'), ('CRT', 'Crate'), ('CRM', 'Cream'), ('CCM', 'Cubic Centimeter'), ('CUFT', 'Cubic Feet'), ('CFM', 'Cubic Feet Per Minute'), ('CFT', 'Cubic Foot'), ('CBM', 'Cubic Meter'), ('CUP', 'Cup'), ('CV', 'Cv'), ('DAILY', 'Daily'), ('DANGLER', 'Dangler'), ('DAY', 'Day'), ('DEZ', 'Daze'), ('DOZ', 'Dozen'), ('DROP', 'Drop'), ('DRM', 'Drum'), ('EA', 'Each'), ('EACH', 'Each'), ('FT', 'Feet'), ('FT2', 'Feet Square'), ('FIT', 'Fit'), ('FLD', 'Fold'), ('FREE', 'Free'), ('FTS', 'Fts'), ('GEL', 'Gel'), ('GLS', 'Glasses'), ('GMS', 'Grams'), ('GGR', 'Great Gross'), ('GRS', 'Gross'), ('GYD', 'Gross Yards'), ('HF', 'Half'), ('HEGAR', 'Hanger'), ('HA', 'Hectare'), ('HMT', 'Helmet'), ('HRS', 'Hours'), ('INJECTION', 'Injection'), ('IN', 'Inches'), ('ITEM ID', 'Item Id'), ('JAR', 'Jars'), ('JL', 'Jhal'), ('JO', 'Jhola'), ('JHL', 'Jhola Jhal'), ('JOB', 'Job'), ('KT', 'Katta'), ('KGS', 'Kilograms'), ('KLR', 'Kiloliter'), ('KME', 'Kilometre'), ('KMS', 'Kilometres'), ('KVA', 'Kilovolt-amp'), ('KW', 'Kilowatt'), ('KIT', 'Kit'), ('LAD', 'Ladi'), ('LENG', 'Length'), ('LBS', 'Libra Pondo'), ('LTR', 'Litre'), ('LOT', 'Lot'), ('LS', 'Lump Sum'), ('MAN-DAY', 'Man-days'), ('MRK', 'Mark'), ('MBPS', 'Mbps'), ('MTR', 'Meters'), ('MMBTU', 'Metric Million British Thermal Unit'), ('MTON', 'Metric Ton'), ('MG', 'Microgram'), ('M/C', 'Millicoulomb'), ('MLG', 'Milligram'), ('MLT', 'Millilitre'), ('MM', 'Millimeter'), ('MINS', 'Minutes'), ('MONTH', 'Month'), ('MON', 'Months'), ('MORA', 'Mora'), ('NIGHT', 'Night'), ('NONE', 'None'), ('NOS', 'Numbers'), ('OINT', 'Ointment'), ('OTH', 'Others'), ('OR', 'Outer'), ('PKG', 'Package'), ('PKT', 'Packets'), ('PAC', 'Packs'), ('PAD', 'Pad'), ('PADS', 'Pads'), ('PAGE', 'Pages'), ('PAIR', 'Pair'), ('PRS', 'Pairs'), ('PATTA', 'Patta'), ('PAX', 'Pax'), ('PER', 'Per'), ('PWP', 'Per Watt Peak'), ('PERSON', 'Persons'), ('PET', 'Peti'), ('PHILE', 'Phile'), ('PCS', 'Pieces'), ('PLT', 'Plates'), ('PT', 'Point'), ('PRT', 'Portion'), ('POCH', 'Pouch'), ('QUAD', 'Quad'), ('QTY', 'Quantity'), ('QTL', 'Quintal'), ('RTI', 'Ratti'), ('REAM', 'Ream'), ('REEL', 'Reel'), ('RIM', 'Rim'), ('ROL', 'Rolls'), ('ROOM', 'Room'), ('RFT', 'Running Foot'), ('RMT', 'Running Meter'), ('RS', 'Rupees'), ('SAC', 'Sachet'), ('SEC', 'Seconds'), ('SEM', 'Semester'), ('SSN', 'Session'), ('SET', 'Sets'), ('SHEET', 'Sheet'), ('SKINS', 'Skins'), ('SLEVES', 'Sleeves'), ('SPRAY', 'Spray'), ('SQCM', 'Square Centimeters'), ('SQF', 'Square Feet'), ('SQY', 'Square Yards'), ('SARAM', 'Saram'), ('STICKER', 'Stickers'), ('STONE', 'Stone'), ('STRP', 'Strips'), ('SYRP', 'Syrup'), ('TBS', 'Tablets'), ('TGM', 'Ten Gross'), ('TKT', 'Ticket'), ('TIN', 'Tin'), ('TON', 'Tonnes'), ('TRY', 'Trays'), ('TRIP', 'Trp'), ('TRK', 'Truck'), ('TUB', 'Tubes'), ('UNT', 'Units'), ('UGS', 'US Gallons'), ('VIAL', 'Vials'), ('W', 'Watt'), ('WEEK', 'Week'), ('YDS', 'Yards'), ('YRS', 'Years')], max_length=10)),
                ('opening_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('low_stock_warning', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('as_of_date', models.DateField(default=django.utils.timezone.now)),
                ('stock_image', models.ImageField(blank=True, null=True, upload_to='stock_images/')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sales_price_without_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sales_price_with_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/')),
                ('hsn_code', models.CharField(default='UNKNOWN', max_length=10)),
                ('gst_tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Create_New_Item.gsttax')),
            ],
        ),
    ]
