# Generated by Django 5.1.7 on 2025-04-26 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('projectmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiring',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.project'),
        ),
        migrations.AddField(
            model_name='hr',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.department'),
        ),
        migrations.AddField(
            model_name='hr',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.location'),
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.location'),
        ),
        migrations.AddField(
            model_name='ar',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.location'),
        ),
        migrations.AddField(
            model_name='manager',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.department'),
        ),
        migrations.AddField(
            model_name='manager',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.location'),
        ),
        migrations.AddField(
            model_name='requests',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.admin'),
        ),
        migrations.AddField(
            model_name='requests',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.employee'),
        ),
        migrations.AddField(
            model_name='requests',
            name='hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.hr'),
        ),
        migrations.AddField(
            model_name='manager',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.shift'),
        ),
        migrations.AddField(
            model_name='hr',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.shift'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.shift'),
        ),
        migrations.AddField(
            model_name='ar',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.shift'),
        ),
        migrations.AddField(
            model_name='skill',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.employee'),
        ),
        migrations.AddField(
            model_name='skill',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.manager'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.department'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.location'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.shift'),
        ),
        migrations.AddField(
            model_name='requests',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.supervisor'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='authentication.manager'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to='authentication.employee'),
        ),
    ]
