# Generated by Django 5.1.7 on 2025-05-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='streams',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
