# Generated by Django 4.2.7 on 2025-07-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_employee_streams'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='manager',
            name='streams',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
