# Generated by Django 4.2.7 on 2025-07-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_admin_features_manager_streams'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='streams',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='streams',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
