# Generated by Django 5.1.7 on 2025-07-17 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_hr_streams_supervisor_streams"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Full-time", "Full-time"),
                            ("Contract", "Contract"),
                            ("Internship-full-time", "Internship (Full-time)"),
                            ("Internship-part-time", "Internship (Part-time)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("posted", models.DateField()),
                ("applications", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Paused", "Paused"),
                            ("Closed", "Closed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "hr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_alerts",
                        to="authentication.hr",
                    ),
                ),
            ],
        ),
    ]
