# Generated by Django 5.1.7 on 2025-07-17 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_jobalert"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_id", models.CharField(editable=False, max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                (
                    "jobTitle",
                    models.CharField(
                        choices=[
                            ("Frontend Developer", "Frontend Developer"),
                            ("Backend Developer", "Backend Developer"),
                            ("UI/UX Designer", "UI/UX Designer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("resumeLink", models.URLField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Resume In Review", "Resume In Review"),
                            ("Shortlisted", "Shortlisted"),
                            ("Interview - L1", "Interview - L1"),
                            ("Interview - L2", "Interview - L2"),
                            ("Interview - L3", "Interview - L3"),
                            ("Welcome Letter", "Welcome Letter"),
                            ("Document Collection", "Document Collection"),
                            ("Offer Letter", "Offer Letter"),
                            ("Onboarding", "Onboarding"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "hr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="authentication.hr",
                    ),
                ),
            ],
        ),
    ]
