# Generated by Django 5.1.7 on 2025-07-17 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_candidate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="resumeLink",
        ),
        migrations.AddField(
            model_name="candidate",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="resumes/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
    ]
