# Generated by Django 5.1.7 on 2025-07-22 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_remove_candidate_resumelink_candidate_resume"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=50, unique=True)),
                ("user_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("gender", models.CharField(max_length=10)),
                (
                    "user_image",
                    models.ImageField(blank=True, null=True, upload_to="user_images/"),
                ),
                ("dob", models.DateField()),
                ("hired_date", models.DateField()),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=100)),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("Employee", "Employee"),
                            ("Supervisor", "Supervisor"),
                            ("Human Resources", "Human Resources"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("state", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                ("linkedin_profile_link", models.URLField(blank=True, null=True)),
                ("reset_token", models.CharField(blank=True, max_length=64, null=True)),
                ("token_expiration", models.DateTimeField(blank=True, null=True)),
                ("reward", models.IntegerField(blank=True, default=0, null=True)),
                ("streams", models.JSONField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.department",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.location",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.shift",
                    ),
                ),
            ],
        ),
    ]
