# Generated by Django 5.1.7 on 2025-08-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_superadmin"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="superadmin",
            options={},
        ),
        migrations.AlterModelManagers(
            name="superadmin",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="superadmin",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="superadmin",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="superadmin",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="superadmin",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="superadmin",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="superadmin",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="superadmin",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="superadmin",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="superadmin",
            name="user_permissions",
        ),
        migrations.AlterField(
            model_name="superadmin",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="superadmin",
            name="password",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="superadmin",
            name="user_id",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="superadmin",
            name="username",
            field=models.CharField(max_length=100),
        ),
    ]
