# Generated by Django 5.1.7 on 2025-08-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0011_alter_superadmin_options_alter_superadmin_managers_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="superadmin",
            name="features",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
