# Generated by Django 5.0.6 on 2025-04-26 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArApplyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ArLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, unique=True)),
                ('medical_leave', models.PositiveIntegerField(default=0)),
                ('vacation_leave', models.PositiveIntegerField(default=0)),
                ('personal_leave', models.PositiveIntegerField(default=0)),
                ('total_leave_days', models.PositiveIntegerField(default=0)),
                ('total_absent_days', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ArNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ArLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('medical', 'Medical'), ('vacation', 'Vacation'), ('personal', 'Personal')], max_length=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('user', models.CharField(default=None, max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('manager_notification_sent', models.BooleanField(default=False)),
                ('ar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.ar')),
            ],
        ),
    ]
