# Generated by Django 5.1.7 on 2025-07-04 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_employee_streams"),
        ("leaves", "0002_arapplynotification_arleavebalance_arnotification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supervisorleaverequest",
            name="is_auto_leave",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the leave was auto-applied due to no check-in.",
            ),
        ),
        migrations.CreateModel(
            name="LateloginReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("supervisor_name", models.CharField(blank=True, max_length=100)),
                (
                    "leave_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leaves.supervisorleaverequest",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.supervisor",
                    ),
                ),
            ],
        ),
    ]
