# Generated by Django 5.1.7 on 2025-07-09 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_employee_streams"),
        ("leaves", "0003_supervisorleaverequest_is_auto_leave_lateloginreason"),
    ]

    operations = [
        migrations.AddField(
            model_name="hrleaverequest",
            name="is_auto_leave",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the leave was auto-applied due to no check-in.",
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="is_auto_leave",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the leave was auto-applied due to no check-in.",
            ),
        ),
        migrations.AddField(
            model_name="managerleaverequest",
            name="is_auto_leave",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the leave was auto-applied due to no check-in.",
            ),
        ),
        migrations.CreateModel(
            name="EmployeeLateLoginReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("employee_name", models.CharField(blank=True, max_length=100)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.employee",
                    ),
                ),
                (
                    "leave_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leaves.leaverequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HrLateLoginReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("hr_name", models.CharField(blank=True, max_length=100)),
                (
                    "hr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.hr",
                    ),
                ),
                (
                    "leave_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leaves.hrleaverequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManagerLateLoginReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("manager_name", models.CharField(blank=True, max_length=100)),
                (
                    "leave_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leaves.managerleaverequest",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.manager",
                    ),
                ),
            ],
        ),
    ]
