# Generated by Django 5.1.7 on 2025-07-25 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_user"),
        ("leaves", "0004_hrleaverequest_is_auto_leave_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hrleaverequest",
            name="hr",
        ),
        migrations.RemoveField(
            model_name="hrleaverequest",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="supervisorleaverequest",
            name="supervisor",
        ),
        migrations.RemoveField(
            model_name="supervisorleaverequest",
            name="user_id",
        ),
        migrations.AlterField(
            model_name="hrleavebalance",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hr_leave_balance",
                to="authentication.user",
            ),
        ),
        migrations.AlterField(
            model_name="hrleaverequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hr_leave_requests",
                to="authentication.user",
            ),
        ),
        migrations.AlterField(
            model_name="leavebalance",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_balance",
                to="authentication.user",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_requests",
                to="authentication.user",
            ),
        ),
        migrations.AlterField(
            model_name="supervisorleavebalance",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supervisor_leave_balance",
                to="authentication.user",
            ),
        ),
        migrations.AlterField(
            model_name="supervisorleaverequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supervisor_leave_requests",
                to="authentication.user",
            ),
        ),
    ]
