# Generated by Django 5.1.7 on 2025-07-28 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_user"),
        ("leaves", "0005_remove_hrleaverequest_hr_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEmpLeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medical_leave", models.PositiveIntegerField(default=0)),
                ("vacation_leave", models.PositiveIntegerField(default=0)),
                ("personal_leave", models.PositiveIntegerField(default=0)),
                ("total_leave_days", models.PositiveIntegerField(default=0)),
                ("total_absent_days", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_emp_leave_balance",
                        to="authentication.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserEmpLeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("medical", "Medical"),
                            ("vacation", "Vacation"),
                            ("personal", "Personal"),
                        ],
                        max_length=10,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "leave_proof",
                    models.FileField(
                        blank=True, null=True, upload_to="media/leave_proof/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("notification_sent", models.BooleanField(default=False)),
                ("calendar_link", models.URLField(blank=True, null=True)),
                (
                    "is_auto_leave",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the leave was auto-applied due to no check-in.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_emp_leave_requests",
                        to="authentication.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserHrLeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medical_leave", models.PositiveIntegerField(default=0)),
                ("vacation_leave", models.PositiveIntegerField(default=0)),
                ("personal_leave", models.PositiveIntegerField(default=0)),
                ("total_leave_days", models.PositiveIntegerField(default=0)),
                ("total_absent_days", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_hr_leave_balance",
                        to="authentication.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserHrLeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("medical", "Medical"),
                            ("vacation", "Vacation"),
                            ("personal", "Personal"),
                        ],
                        max_length=10,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(max_length=30)),
                ("manager_notification_sent", models.BooleanField(default=False)),
                (
                    "is_auto_leave",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the leave was auto-applied due to no check-in.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_hr_leave_requests",
                        to="authentication.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSupervisorLeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medical_leave", models.PositiveIntegerField(default=0)),
                ("vacation_leave", models.PositiveIntegerField(default=0)),
                ("personal_leave", models.PositiveIntegerField(default=0)),
                ("total_leave_days", models.PositiveIntegerField(default=0)),
                ("total_absent_days", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_supervisor_leave_balance",
                        to="authentication.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSupervisorLeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("medical", "Medical"),
                            ("vacation", "Vacation"),
                            ("personal", "Personal"),
                        ],
                        max_length=10,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(max_length=30)),
                ("supervisor_notification_sent", models.BooleanField(default=False)),
                (
                    "is_auto_leave",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the leave was auto-applied due to no check-in.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_supervisor_leave_requests",
                        to="authentication.user",
                    ),
                ),
            ],
        ),
    ]
