# Generated by Django 5.1.7 on 2025-07-28 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0006_userempleavebalance_userempleaverequest_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userempleaverequest",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userhrleavebalance",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userhrleaverequest",
            name="user",
        ),
        migrations.RemoveField(
            model_name="usersupervisorleavebalance",
            name="user",
        ),
        migrations.RemoveField(
            model_name="usersupervisorleaverequest",
            name="user",
        ),
        migrations.DeleteModel(
            name="UserEmpLeaveBalance",
        ),
        migrations.DeleteModel(
            name="UserEmpLeaveRequest",
        ),
        migrations.DeleteModel(
            name="UserHrLeaveBalance",
        ),
        migrations.DeleteModel(
            name="UserHrLeaveRequest",
        ),
        migrations.DeleteModel(
            name="UserSupervisorLeaveBalance",
        ),
        migrations.DeleteModel(
            name="UserSupervisorLeaveRequest",
        ),
    ]
