# Generated by Django 5.1.7 on 2025-09-23 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_superadmin_features"),
        ("leaves", "0007_remove_userempleaverequest_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("medical", "Medical"),
                            ("vacation", "Vacation"),
                            ("personal", "Personal"),
                        ],
                        max_length=10,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "leave_proof",
                    models.FileField(
                        blank=True, null=True, upload_to="media/leave_proof/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("notification_sent", models.BooleanField(default=False)),
                ("calendar_link", models.URLField(blank=True, null=True)),
                (
                    "is_auto_leave",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the leave was auto-applied due to no check-in.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_leave_requests",
                        to="authentication.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserLateLoginReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_late_login_reasons",
                        to="authentication.user",
                    ),
                ),
                (
                    "leave_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_late_login_reasons",
                        to="leaves.userleaverequest",
                    ),
                ),
            ],
        ),
    ]
