# Generated by Django 5.1.7 on 2025-04-26 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('bonus_type', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=20)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('paid_status', models.CharField(blank=True, max_length=20, null=True)),
                ('total_paid', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HrPayrollNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=40)),
                ('user_id', models.CharField(max_length=30)),
                ('date', models.DateField(default=True)),
                ('time', models.TimeField()),
                ('message', models.TextField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HrSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('annual_salary', models.CharField(max_length=20)),
                ('bonus', models.CharField(max_length=20)),
                ('total_salary', models.CharField(blank=True, max_length=20, null=True)),
                ('monthly_salary', models.CharField(blank=True, max_length=20, null=True)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerPayrollNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=40)),
                ('user_id', models.CharField(max_length=30)),
                ('date', models.DateField(default=True)),
                ('time', models.TimeField()),
                ('message', models.TextField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('annual_salary', models.CharField(max_length=20)),
                ('bonus', models.CharField(max_length=20)),
                ('total_salary', models.CharField(blank=True, max_length=20, null=True)),
                ('monthly_salary', models.CharField(blank=True, max_length=20, null=True)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=40)),
                ('user_id', models.CharField(max_length=30)),
                ('date', models.DateField(default=True)),
                ('time', models.TimeField()),
                ('message', models.TextField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('annual_salary', models.CharField(max_length=20)),
                ('bonus', models.CharField(max_length=20)),
                ('total_salary', models.CharField(blank=True, max_length=20, null=True)),
                ('monthly_salary', models.CharField(blank=True, max_length=20, null=True)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorPayrollNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=40)),
                ('user_id', models.CharField(max_length=30)),
                ('date', models.DateField(default=True)),
                ('time', models.TimeField()),
                ('message', models.TextField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('annual_salary', models.CharField(max_length=20)),
                ('bonus', models.CharField(max_length=20)),
                ('total_salary', models.CharField(blank=True, max_length=20, null=True)),
                ('monthly_salary', models.CharField(blank=True, max_length=20, null=True)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HrPayrollManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('month', models.DateField()),
                ('email', models.EmailField(blank=True, default=True, max_length=254)),
                ('base_salary', models.CharField(max_length=20)),
                ('net_salary', models.CharField(default='0', max_length=20)),
                ('total_working_hours', models.CharField(default='0', max_length=20)),
                ('overtime_hours', models.CharField(default='0', max_length=20)),
                ('overtime_pay', models.CharField(default='0', max_length=30)),
                ('pdf_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'unique_together': {('user_id', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ManagerPayrollManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('month', models.DateField()),
                ('email', models.EmailField(blank=True, default=True, max_length=254)),
                ('base_salary', models.CharField(max_length=20)),
                ('net_salary', models.CharField(default='0', max_length=20)),
                ('total_working_hours', models.CharField(default='0', max_length=20)),
                ('overtime_hours', models.CharField(default='0', max_length=20)),
                ('overtime_pay', models.CharField(default='0', max_length=30)),
                ('pdf_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'unique_together': {('user_id', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PayrollManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('month', models.DateField()),
                ('email', models.EmailField(blank=True, default=True, max_length=254)),
                ('base_salary', models.CharField(max_length=20)),
                ('net_salary', models.CharField(default='0', max_length=20)),
                ('total_working_hours', models.CharField(default='0', max_length=20)),
                ('overtime_hours', models.CharField(default='0', max_length=20)),
                ('overtime_pay', models.CharField(default='0', max_length=30)),
                ('pdf_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'unique_together': {('user_id', 'month')},
            },
        ),
        migrations.CreateModel(
            name='SupervisorPayrollManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('month', models.DateField()),
                ('email', models.EmailField(blank=True, default=True, max_length=254)),
                ('base_salary', models.CharField(max_length=20)),
                ('net_salary', models.CharField(default='0', max_length=20)),
                ('total_working_hours', models.CharField(default='0', max_length=20)),
                ('overtime_hours', models.CharField(default='0', max_length=20)),
                ('overtime_pay', models.CharField(default='0', max_length=30)),
                ('pdf_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'unique_together': {('user_id', 'month')},
            },
        ),
    ]
