# Generated by Django 5.1.7 on 2025-09-18 04:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_superadmin_features"),
        ("payroll", "0002_arpayrollnotification_arsalary_arpayrollmanagement"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPayrollNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("time", models.TimeField(auto_now_add=True)),
                ("message", models.TextField(default="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_notifications",
                        to="authentication.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-time"],
            },
        ),
        migrations.CreateModel(
            name="UserSalary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annual_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "bonus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "monthly_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("effective_date", models.DateField(default=django.utils.timezone.now)),
                ("updated_date", models.DateField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salaries",
                        to="authentication.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPayrollManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("base_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "net_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_working_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "overtime_pay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("pdf_path", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payrolls",
                        to="authentication.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_id", "month")},
            },
        ),
    ]
