# Generated by Django 5.1.7 on 2025-05-16 05:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Create_New_Item', '0001_initial'),
        ('Pincode', '0001_initial'),
        ('Sales_Person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('sent', 'Sent'), ('converted', 'Converted to Invoice')], default='created', max_length=30)),
                ('so_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('po_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('so_date', models.DateField(default=django.utils.timezone.localdate)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(limit_choices_to={'party_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, to='Pincode.addparty')),
                ('sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sales_Person.salesperson')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSalesOrderEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='Sales_Order.clientsalesorder')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('hsn_sac_code', models.CharField(blank=True, max_length=20, null=True)),
                ('measuring_unit', models.CharField(blank=True, max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_item', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Create_New_Item.productitem')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Sales_Order.clientsalesorder')),
                ('service_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Create_New_Item.serviceitem')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Create_New_Item.gsttax')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSalesOrderTotalAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sales_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='total_amount', to='Sales_Order.clientsalesorder')),
            ],
        ),
    ]
