# Generated by Django 5.1.7 on 2025-07-19 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_remove_candidate_resumelink_candidate_resume"),
        ("projectmanagement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("title", models.CharField(max_length=100)),
                ("experience_level", models.CharField(max_length=50)),
                ("job_types", models.CharField(max_length=50)),
                ("opening_roles", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("hr_review", "HR Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "hr_reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_position_requests",
                        to="authentication.hr",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_requests",
                        to="authentication.location",
                    ),
                ),
                (
                    "manager_approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_position_requests",
                        to="authentication.manager",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_requests",
                        to="authentication.employee",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projectmanagement.role",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vacancy_id",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("title", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("experience_level", models.CharField(max_length=50)),
                ("job_types", models.CharField(max_length=50)),
                ("opening_roles", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "position_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancy",
                        to="projectmanagement.positionrequest",
                    ),
                ),
            ],
        ),
    ]
