# Generated by Django 5.1.7 on 2025-07-22 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projectmanagement", "0002_positionrequest_vacancy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="positionrequest",
            name="rejection_reason",
        ),
    ]
