# Generated by Django 5.1.7 on 2025-07-25 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_user"),
        ("projectmanagement", "0005_alter_team_team_leader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                related_name="team_members", to="authentication.user"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="team_leader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leader_teams",
                to="authentication.user",
            ),
        ),
    ]
