# Generated by Django 5.1.7 on 2025-05-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('target', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deals_closed', models.PositiveIntegerField(default=0)),
                ('clients_handled', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='sales_profiles/')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
