# Generated by Django 5.1.7 on 2025-05-17 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales_Person', '0001_initial'),
        ('authentication', '0003_employee_streams'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesperson_profile', to='authentication.employee'),
        ),
    ]
