# Generated by Django 5.1.7 on 2025-05-16 05:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Create_New_Item', '0001_initial'),
        ('Pincode', '0001_initial'),
        ('Sales_Person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_challan_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('delivery_challan_date', models.DateField(default=django.utils.timezone.localdate)),
                ('party_name', models.CharField(blank=True, max_length=255)),
                ('party_mobile_number', models.CharField(blank=True, max_length=15)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10)),
                ('status', models.CharField(choices=[('Open', 'open'), ('Delivered', 'delivered')], default='Open', max_length=30)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_challans', to='Pincode.addparty')),
                ('sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_challan', to='Sales_Person.salesperson')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryChallanEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('delivery_challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='Delivery_Challan.deliverychallan')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryChallanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('hsn_sac_code', models.CharField(blank=True, max_length=20, null=True)),
                ('measuring_unit', models.CharField(blank=True, max_length=10)),
                ('price_per_item', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_challan_items', to='Delivery_Challan.deliverychallan')),
                ('product_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_challan_items', to='Create_New_Item.productitem')),
                ('service_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_challan_services', to='Create_New_Item.serviceitem')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Create_New_Item.gsttax')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryChallanTotalAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('delivery_challan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='total_amount', to='Delivery_Challan.deliverychallan')),
            ],
        ),
    ]
