# Generated by Django 5.1.7 on 2025-05-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armanagement', '0002_clientar_employeear_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='employee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
