# Generated by Django 5.1.7 on 2025-06-09 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pincode", "0001_initial"),
        ("Sales_Person", "0002_salesperson_employee"),
        ("armanagement", "0003_alter_target_client_alter_target_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="arclienttarget",
            name="sales_person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ar_client_targets",
                to="Sales_Person.salesperson",
            ),
        ),
        migrations.AddConstraint(
            model_name="arclienttarget",
            constraint=models.UniqueConstraint(
                fields=("client", "sales_person", "start_date", "end_date"),
                name="unique_target_per_client_salesperson_date",
            ),
        ),
    ]
