# Generated by Django 5.1.7 on 2025-04-26 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.employee'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.hr'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.location'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.manager'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.shift'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.supervisor'),
        ),
        migrations.AddField(
            model_name='attendanceoverview',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='authentication.employee'),
        ),
        migrations.AddField(
            model_name='permissionhour',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.employee'),
        ),
        migrations.AddField(
            model_name='permissionhour',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.manager'),
        ),
        migrations.AddField(
            model_name='resetrequest',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.employee'),
        ),
        migrations.AddField(
            model_name='resetrequest',
            name='hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.hr'),
        ),
        migrations.AddField(
            model_name='resetrequest',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.manager'),
        ),
        migrations.AddField(
            model_name='resetrequest',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.supervisor'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.manager'),
        ),
        migrations.AddField(
            model_name='shift_attendance',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.employee'),
        ),
    ]
