# Generated by Django 5.0.6 on 2025-04-26 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.ar'),
        ),
        migrations.AddField(
            model_name='resetrequest',
            name='ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.ar'),
        ),
    ]
