# Generated by Django 5.1.7 on 2025-07-25 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_attendance_ar_resetrequest_ar"),
        ("authentication", "0009_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.user",
            ),
        ),
        migrations.AddField(
            model_name="resetrequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.user",
            ),
        ),
    ]
