# Generated by Django 5.1.7 on 2025-07-28 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_userattendance_userresetrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userresetrequest",
            name="ar",
        ),
        migrations.RemoveField(
            model_name="userresetrequest",
            name="manager",
        ),
        migrations.RemoveField(
            model_name="userresetrequest",
            name="user",
        ),
        migrations.DeleteModel(
            name="UserAttendance",
        ),
        migrations.DeleteModel(
            name="UserResetRequest",
        ),
    ]
