# Generated by Django 5.1.7 on 2025-07-29 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_remove_userresetrequest_ar_and_more"),
        ("authentication", "0009_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="permissionhour",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.user",
            ),
        ),
    ]
