# Generated by Django 5.1.7 on 2025-08-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_permissionhour_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("Present", "Present"),
                    ("Late", "Late"),
                    ("Absent", "Absent"),
                    ("Half Day", "Half Day"),
                ],
                default="Present",
                max_length=10,
            ),
        ),
    ]
